### ISSUE TITLE
Docker image cannot be pulled down

### ISSUE THREAD

**Issue by ponder-lxl** [clearhanhui/LearnLibTorch#3]
Docker image cannot be pulled down：
Hello, I encountered an issue with the dropdown image while using your warehouse：
![局部截取_20241217_232511](https://github.com/user-attachments/assets/42b89542-0d02-48c9-adb4-61f323456fb5)

**Comment by clearhanhui** [comment]
> Docker image cannot be pulled down： Hello, I encountered an issue with the dropdown image while using your warehouse： ![局部截取_20241217_232511](https://private-user-images.githubusercontent.com/129484066/396557866-42b89542-0d02-48c9-adb4-61f323456fb5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NTM0MzIsIm5iZiI6MTczNDQ1MzEzMiwicGF0aCI6Ii8xMjk0ODQwNjYvMzk2NTU3ODY2LTQyYjg5NTQyLTBkMDItNDhjOS1hZGI0LTYxZjMyMzQ1NmZiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNjMyMTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzFiNmI2MzZkMGNkMTliMDAwZGMwZDdmOWQ0ZjBhZWNiNDk2OTNhMTIyYzg5NDA3NmI2Njg3MDYwNGNlNDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Uurt01hNvWm-GMLA4mBTv45KEGEaQGAJoqCbdDH6nk0)


I think it‘s network issue. There's a copy on aliyun:
``` shell
docker pull crpi-7p1lmijmzs6f2s62.cn-hangzhou.personal.cr.aliyuncs.com/clearhanhui/ubuntu-libtorch-{cpu/cuda}
docker run -it crpi-7p1lmijmzs6f2s62.cn-hangzhou.personal.cr.aliyuncs.com/clearhanhui/ubuntu-libtorch-{cpu/cuda}:latest
```
